### ISSUE TITLE
chord:modifier missing when note tied to preceding note

### ISSUE THREAD

**Issue by masthom** [jimjonesbr/musicowl#8]
Thanks for this great converter (and the ontology)!

I think there is an issue with `chord:modifier` on notes that are tied to preceding notes: 

This is a simple example: 

![Ties_Example](https://user-images.githubusercontent.com/53256309/128538931-b3d169a2-94f7-41d2-a0bf-868cb13e2eae.png)

Converting a corresponding XML file to MusicOWL, the pitches of the six notes are converted as follows (missing parts added as ##comments): 

```
node:a2da4aed-f485-42df-9278-24cf5cfb34f5_MOV1_P1_M1_NS_1_NOTE_0
        a               chord:Note ;
        mso:hasOctave   "4"^^xsd:int ;
        chord:modifier  chord:sharp ;
        chord:natural   note:F .

node:a2da4aed-f485-42df-9278-24cf5cfb34f5_MOV1_P1_M2_NS_2_NOTE_0 
        a              chord:Note ;
        mso:hasOctave  "4"^^xsd:int ;
**##missing: chord:modifier	chord:sharp ;**
	chord:natural  note:F . 


node:a2da4aed-f485-42df-9278-24cf5cfb34f5_MOV1_P1_M2_NS_3_NOTE_1
        a              chord:Note ;
        mso:hasOctave  "4"^^xsd:int ;
        chord:natural  note:F .

node:a2da4aed-f485-42df-9278-24cf5cfb34f5_MOV1_P1_M3_NS_4_NOTE_0
        a              chord:Note ;
        mso:hasOctave  "4"^^xsd:int ;
        chord:natural  note:F .

node:a2da4aed-f485-42df-9278-24cf5cfb34f5_MOV1_P1_M3_NS_5_NOTE_1
        a               chord:Note ;
        mso:hasOctave   "4"^^xsd:int ;
        chord:modifier  chord:flat ;
        chord:natural   note:F .

node:a2da4aed-f485-42df-9278-24cf5cfb34f5_MOV1_P1_M4_NS_6_NOTE_0
        a              chord:Note ;
        mso:hasOctave  "4"^^xsd:int ;
**##missing: chord:modifier  chord:flat ;**
        chord:natural  note:F .
```

If one queries the turtle file with SPARQL, the first note of ms. 2 will not be among the expected results when searching for F sharp. Likewise, the first note of ms. 5 will not be among the expected results when searching for F flat.

Here is the corresponding MusicXML for the first two notes ( F sharp):

...NS_1_NOTE_0:
```
<note default-x="83">
        <pitch>
          <step>F</step>
          <alter>1</alter>
          <octave>4</octave>
        </pitch>
        <duration>4</duration>
        <tie type="start"/>
        <voice>1</voice>
        <type>half</type>
        <accidental>sharp</accidental>
        <stem default-y="0">up</stem>
        <notations>
          <tied type="start"/>
        </notations>
      </note>

```
...NS_2_NOTE_0: 
```
<note default-x="13">
        <pitch>
          <step>F</step>
          <alter>1</alter>
          <octave>4</octave>
        </pitch>
        <duration>2</duration>
        <tie type="stop"/>
        <voice>1</voice>
        <type>quarter</type>
        <stem default-y="0">up</stem>
        <notations>
          <tied type="stop"/>
        </notations>
      </note>
```

Just a guess (I don't understand the Java code well enough, sorry): the converter looks for the `<accidental>` element when deciding whether to place `chord:modifier` or not? Instead of looking for the values of `<alter>`?

**Comment by jimjonesbr** [comment]
Hello there. Thanks for reporting and for the kind words.
Due to lack of funding I had to abandon this project a few years ago, but I'm glad to take a look at this bug. I wrote more than 50 automated tests, but it seems I didn't exhaust all possibilities :) Could you send me the XML file that is causing the problem (or a fraction of it), so that I can reproduce the issue myself? 

If remember it correctly, I wrote the script to set the accidentals of a note based on the key, or in case it is changed in a certain measure all subsequent notes inherit the "new" accidental. As a matter of fact, I even wrote a few test cases to cover that... so I might have forgot something. I haven't touched this code in a while, so I hope it doesn't take too long for me to find the problem. If you could send me the file, it would help a lot.

Cheers,
Jim

**Comment by masthom** [comment]
Hi!

Thanks for the quick reply. Here's the XML file:

[Accid_Tie_Test_xml.txt](https://github.com/jimjonesbr/musicowl/files/6949150/Accid_Tie_Test_xml.txt)

I modified it a bit to show some more details: In fact, the `chord:modifier` statements are only missing if the note is tied to a note in a preceding measure. If the preceding note is in the same measure all is fine.

![Accid_Tie_Test](https://user-images.githubusercontent.com/53256309/128601729-c66c0b36-34bb-4879-ad81-157a7195323d.png)

So the issue only occurs with the first notes in a measure: "..._NOTE_0", in this example ms. 2 (F sharp) and ms. 4 (F flat). 

```
node:56db3f19-5f9b-4afc-9841-d47e8ec2b359_MOV1_P1_M2_NS_4_NOTE_0
        a              chord:Note ;
        mso:hasOctave  "4"^^xsd:int ;
        chord:natural  note:F .
```

```
node:56db3f19-5f9b-4afc-9841-d47e8ec2b359_MOV1_P1_M4_NS_12_NOTE_0
        a              chord:Note ;
        mso:hasOctave  "4"^^xsd:int ;
        chord:natural  note:F .
```

I am attaching also the resulting TTL file: 
[Accid_Tie_Test_ttl.txt](https://github.com/jimjonesbr/musicowl/files/6949172/Accid_Tie_Test_ttl.txt)

Thank you for taking the time! 

Best regards, Thomas

**Comment by jimjonesbr** [comment]
Hi Thomas,

I just pushed a bug fix. Could you test it?

Best, Jim

**Comment by masthom** [comment]
Sorry, looks like "Music2RDF Converter 1.3.7" is not running properly - or at least not on my system. I am attaching the reports from the console (versions 1.3.6 vs. 1.3.7): 
[Reports_MusicOWL136vs137.txt](https://github.com/jimjonesbr/musicowl/files/6953996/Reports_MusicOWL136vs137.txt)

**Comment by jimjonesbr** [comment]
That's odd. The code runs in my machine. Can you send me the metadata file you're using?

**Comment by jimjonesbr** [comment]
It does work with this [metadata file](https://github.com/jimjonesbr/musicowl/blob/master/musicowl/musicxml/metadata-file/metadata.xml) using `1.3.7` and `1.3.8` (new bug fixes).

[output-1.3.8.txt](https://github.com/jimjonesbr/musicowl/files/6954555/output-1.3.8.txt)
[output-1.3.7.txt](https://github.com/jimjonesbr/musicowl/files/6954556/output-1.3.7.txt)

**Comment by masthom** [comment]
Ok, I see... I've been using a metadata file with some outdated (?) labels for some of the elements, like `<title>` instead of `<scoreTitle>`, `<collectionName>` instead of `<collectionLabel>` etc. (The old labels worked fine with `1.3.6`.) Now `1.3.7` runs perfectly well and all expected `chord:modifier` statements are appearing. Thank you!
For `1.3.8` I probably have to check my java installation...  Receiving this report:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/wwu/music2rdf/converter/Converter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

```
For now I am fine with `1.3.7`! Thanks a lot again!
Best, Thomas

**Comment by jimjonesbr** [comment]
Nice it finally worked. 

Yes, I had an outdated version of the metadata file. I will also update the documentation and then the maven repo.

Regarding: 1.3.8: I had to upgrade loads of libraries, as the converter was using outdated and unsafe dependencies. I also corrected a bug related to this issue: https://github.com/jimjonesbr/musicowl/commit/7184e31afef2df894186e26c2571025873b33b22 .. so I recommend you use it :) To use 1.3.8 you need to install Java 11 or greater.  Could you please test it? If it works I can close this issue.

If you don't mind my asking: what is your project about? I haven't heard any feedback from the ontology in a while, so I am surprised anyone still uses it :)

**Comment by masthom** [comment]
Hi Jim,
I finally got my old computer to digest a newer java version.... As expected: `1.3.8` also runs without problems. 

Thanks for asking: I work as a musicologist with Stefan Münnich, who had already contacted you some time ago about MusicOWL and who drew my attention to it. (Best regards from him!)
In fact, last semester we organized a little course on music encoding formats at the University of Basel, in which we also dedicated a session to MusicOWL!
To be honest: My involvement with MusicOWL is not really a project at the moment. But I find the approach of RDF graphs for music representation very interesting and experiment from time to time with it to make it (maybe) fruitful for the (e.g. harmonic) analysis of especially post-tonal music (like Anton Webern's).

Thanks again!
Best, Thomas

**Comment by jimjonesbr** [comment]
Hi Thomas,

I'm glad it now works as expected. 
I also find graphs much more suitable to work with music data than relational data models. However, my experience with RDF Triple Stores isn't the best, as complex SPARQL Queries don't have much room for optimization and they can get very slow for today's standards. Sometime ago I experimented importing and querying MusciOWL data sets into Neo4j, which was incredibly fast and easy to use (Cypher is much more intuitive than SPARQL), but last time I checked the reasoning possibilities were rather limited and you had to program your own rules. 

Have fun with your experiments and please tell Stefan that I send my regards! 

Best, Jim
